name: Homebrew Updater

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */2 * * *"

jobs:
  homebrewUpdater:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        
      - name: Download Goose Mod
        run: wget https://github.com/GooseMod/GooseMod/raw/dist-dev/goosemod.js -nv
        
      - name: Build Topaz
        run: |
          git clone https://github.com/GooseMod/topaz
          cd topaz
          node bundle.js
          cd ..
          mv topaz/out.js topaz.js
          rm -rf topaz
          
      - name: Commit Changes
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add . || exit 0
          git commit -m 'Updates SDRoot' || exit 0
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
